#!/usr/bin/env python3
import sys
import argparse
import pickle
from utils import UnlabeledReader

def parse_args():
    parser = argparse.ArgumentParser(
        description="Decodes POS tags using given model", 
        epilog="Author: Matous Machacek <machacekmatous@gmail.com>")
    
    parser.add_argument("model",
            #help="A file with model to be used to decode sentences.",
            type=argparse.FileType('rb'),
            )
    
    parser.add_argument("data",
            #help="A corpus to be decoded. It should be contain one tokenized sentence per line. Ommit or use '-' for stdin",
            nargs='?',
            default=UnlabeledReader('-'),
            type=UnlabeledReader,
            )

    return parser.parse_args()

def main():
    args = parse_args()
    tagger = pickle.load(args.model)
    for word, tag in tagger.decode(args.data):
        print("%s/%s" % (word,tag))

if __name__ == '__main__':
    main()
