#!/usr/bin/env python3
import sys
import argparse
import pickle
from baseline import BaselineTagger
from utils import LabeledReader

def parse_args():
    parser = argparse.ArgumentParser(
        description="Trains baseline model for POS tagging", 
        epilog="Author: Matous Machacek <machacekmatous@gmail.com>")
    
    parser.add_argument("train",
            help="A file in spl format with training data, use '-' for stdin",
            type=LabeledReader,
            )
    
    parser.add_argument("model",
            help="A file where the created model will be stored. Omit for stdout",
            type=argparse.FileType('wb'),
            )

    return parser.parse_args()

def main():
    args = parse_args()
    tagger = BaselineTagger()
    tagger.train_labeled(args.train)
    pickle.dump(tagger, args.model)

if __name__ == '__main__':
    main()
