#!/usr/bin/env python3
import sys
import argparse
import pickle

def parse_args():
    parser = argparse.ArgumentParser(
        description="Trains HMM model for POS tagging", 
        epilog="Author: Matous Machacek <machacekmatous@gmail.com>")
    
    parser.add_argument("model",
            help="A file with model to be used to decode sentences.",
            type=argparse.FileType('rb'),
            )
    
    parser.add_argument("corpus",
            help="A corpus to be decoded. It should be contain one tokenized sentence per line. Ommit or use '-' for stdin",
            nargs='?',
            default=SentenceReader('-'),
            type=SentenceReader,
            )

    return parser.parse_args()

def main():
    args = parse_args()
    tagger = pickle.load(args.model)
    for decoded_sentence in tagger.decode(args.corpus):
        print(*["%s/%s" % (word,tag) for word, tag in decoded_sentence])


class SentenceReader(object):
    def __init__(self, filename):
        if filename == '-':
            self.file = sys.stdin
        else:
            self.file = open(filename, mode='r', encoding='utf-8')

    def __iter__(self):
        for line in self.file:
            yield line.split()

    def __del__(self):
        if self.file is not sys.stdin:
            self.file.close()

if __name__ == '__main__':
    main()
