#!/usr/bin/env python3
import sys
import argparse
import itertools
import collections

def parse_args():
    parser = argparse.ArgumentParser(
        description="Creates the lexicon file for the Brill's tagger", 
        epilog="Author: Matous Machacek <machacekmatous@gmail.com>")
    
    parser.add_argument("input",
            help="A file in ptg format, omit or '-' for stdin",
            metavar="FILE_PTG",
            nargs='?',
            default=sys.stdin,
            type=argparse.FileType('r'),
            )

    return parser.parse_args()
args = parse_args()

def main():
    tag_counters = collections.defaultdict(collections.Counter)
    for line in args.input:
        for item in line.split():
            word, tag = item.split('/',2) 
            tag_counters[word][tag] += 1
    
    for word, tag_counter in tag_counters.items():
        tags_by_count = [tag for tag, count in tag_counter.most_common()]
        print(word, *tags_by_count)

if __name__ == '__main__':
    main()
