#!/usr/bin/env python3
import sys
import argparse
import itertools
import collections

def parse_args():
    parser = argparse.ArgumentParser(
        description="Creates the lexicon file for the Brill's tagger", 
        epilog="Author: Matous Machacek <machacekmatous@gmail.com>")
    
    parser.add_argument("input",
            help="A file in ptg format, omit or '-' for stdin",
            metavar="FILE_PTG",
            default=sys.stdin,
            type=argparse.FileType('r'),
            )

    return parser.parse_args()
args = parse_args()

def main():
    sorted_lines = sorted(line.strip().split('/',2) for line in args.input)
    for word, group in itertools.groupby(sorted_lines, key=lambda x: x[0]):
        tags = collections.Counter(tag for word, tag in group)
        sorted_by_count = [tag for tag, count in tags.most_common()]
        print(word, *sorted_by_count)

if __name__ == '__main__':
    main()
