#!/usr/bin/env python3
import sys
import argparse
import itertools
import collections

def parse_args():
    parser = argparse.ArgumentParser(
        description="Lists of all words occurring in FILE_UNTAGGED, sorted by decreasing frequency.", 
        epilog="Author: Matous Machacek <machacekmatous@gmail.com>")
    
    parser.add_argument("input",
            help="A file with one sentence per line, omit or '-' for stdin",
            metavar="FILE_UNTAGGED",
            nargs='?',
            default=sys.stdin,
            type=argparse.FileType('r'),
            )

    return parser.parse_args()
args = parse_args()

def main():
    counter = collections.Counter()
    for line in args.input:
        counter.update(line.split())
    for word, count in counter.most_common():
        print(word)

if __name__ == '__main__':
    main()
