#!/usr/bin/env python3
import sys
import argparse
from itertools import zip_longest

def parse_args():
    parser = argparse.ArgumentParser(
        description="Measures the accuracy of given tagged text", 
        epilog="Author: Matous Machacek <machacekmatous@gmail.com>")
    
    parser.add_argument("guessed",
            help="A file with guessed tags in spl format, omit or '-' for stdin",
            default=sys.stdin,
            type=argparse.FileType('r'),
            )
    
    parser.add_argument("golden",
            help="A file with golden tags in spl format, omit or '-' for stdin",
            default=sys.stdin,
            type=argparse.FileType('r'),
            )

    return parser.parse_args()
args = parse_args()

def main():
    correct, all = 0, 0
    for guessed_line, golden_line in zip_longest(args.guessed, args.golden):
        for guessed_item, golden_item in zip_longest(guessed_line.split(), golden_line.split()):
            guessed_word, guessed_tag = guessed_item.split('/',2)
            golden_word, golden_tag = golden_item.split('/',2)
            assert guessed_word == golden_word
            if guessed_tag == golden_tag:
                correct += 1
            all += 1
    print(correct/all)

if __name__ == '__main__':
    main()
